### ISSUE TITLE
UI errors

### ISSUE THREAD

**Issue by ridgekimani** [andela/wger-sparta#18]
There are some of the UI issues that I think needs to be addressed... There are some inconsistencies that are present in the code...
Check out for the inconsistencies especially if you added custom CSS to the repo...
I think for the ones who worked on the UI part should check this out

<img width="614" alt="screen shot 2017-10-17 at 6 46 26 pm" src="https://user-images.githubusercontent.com/15478648/31674844-8c82b330-b36b-11e7-8445-f8bd17cf4b7a.png">
<img width="596" alt="screen shot 2017-10-17 at 6 46 00 pm" src="https://user-images.githubusercontent.com/15478648/31674845-8cb54c64-b36b-11e7-9873-792d6d112727.png">

**Comment by Lemmah** [comment]
The same extends to the nutrition page... the options button grew a little bit larger on this second iteration.

**Comment by ridgekimani** [comment]
The guys who worked on the css should check that out

**Comment by Gidraff** [comment]
The css error is not coming from the file I was working on.I was working from the feature subfolder under software folder.

**Comment by Descartess** [comment]
this has been resolved under PR fix-css- scoping bugs #19
