### ISSUE TITLE
ft #151593384 Integration with circle CI

### ISSUE THREAD

**Issue by ridgekimani** [andela/wger-sparta#9]
-- Currently circle CI is integrated for continuous integration, but for some reason **tests are not working unless you push local configurations for the settings.py file**

-- Consider **adding the configurations for generating a settings.py file in the yaml file** of the Circle CI to avoid multiple settings.py configurations from multiple contributors

**Comment by john555** [comment]
@ridgekimani there is already code to generate the settings.py
